# Generated by Django 3.2.13 on 2022-07-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("joyous", "0018_alter_closedfor_id_alter_eventcategory_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="closedfor",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="eventcategory",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
