# https://github.com/linuxsoftware/ls.joyous

dist: xenial

language: python

cache: pip

env:
 - WAGTAIL_VERSION=6.3
 - WAGTAIL_VERSION=7.0
 - WAGTAIL_VERSION=7.1

python:
  - "3.10"
  - "3.11"
  - "3.12"
  - "3.13"

install:
  - pip install -r requirements.txt
  - pip install wagtail==$WAGTAIL_VERSION

script:
  - ./runtests.py --coverage

after_success:
  - coveralls
