name: CI

on:
  pull_request:
    branches: ["master", "main"]
    paths-ignore: ["docs/**"]

  push:
    branches: ["master", "main"]
    paths-ignore: ["docs/**"]
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  lint:
    name: Lint (flake8)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Set up Python and install flake8
        run: |
          uv python install 3.12
          uv venv --python 3.12
          uv pip install flake8

      - name: Run flake8
        run: uv run flake8 ls/joyous

  test:
    name: Tests (Python ${{ matrix.python }}, Django ${{ matrix.django }}, Wagtail ${{ matrix.wagtail }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # Django 4.2 LTS + Wagtail 6.3 across all Python versions
          - python: "3.10"
            django: "4.2"
            wagtail: "6.3"
          - python: "3.11"
            django: "4.2"
            wagtail: "6.3"
          - python: "3.12"
            django: "4.2"
            wagtail: "6.3"
          - python: "3.13"
            django: "4.2"
            wagtail: "6.3"
          # Custom combinations for other versions
          - python: "3.11"
            django: "5.1"
            wagtail: "6.3"
          - python: "3.12"
            django: "5.1"
            wagtail: "7.0"
          - python: "3.12"
            django: "5.2"
            wagtail: "7.0"
          - python: "3.13"
            django: "5.2"
            wagtail: "7.1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Set up Python ${{ matrix.python }}
        run: uv python install ${{ matrix.python }}

      - name: Run tests with coverage
        run: |
          uv run --python ${{ matrix.python }} \
            --with "django~=${{ matrix.django }}.0" \
            --with "wagtail~=${{ matrix.wagtail }}.0" \
            --with-requirements requirements.txt \
            python ./runtests.py --pytest --coverage

      - name: Upload coverage HTML (artifact)
        if: matrix.python == '3.12' && matrix.django == '4.2' && matrix.wagtail == '6.3'
        uses: actions/upload-artifact@v4
        with:
          name: htmlcov
          path: htmlcov
